---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
  namespace: estudo-redis-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: devops-app
          image: devops/app:1.1.1
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "300m"
          ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: estudo-redis-app
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    name: tcp
  selector:
    app: redis-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-app-ingress
  namespace: estudo-redis-app
  annotations:
    ingressClassName: "traefik"
spec:
  rules:
  - host: "www.172.18.0.2.sslip.io"
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: devops-app-service
              port:
                number: 8081